require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
use_frameworks!

# uncomment STATIC_LIBRARIES to compensate for missing archs when building on M1
STATIC_LIBRARIES = [
  'RNScreens',
  'react-native-compass-heading',
  'react-native-safe-area-context',
  'react-native-mapbox-gl',
  'RNVectorIcons',
  'RNCMaskedView',
  'RNDefaultPreference',
  'react-native-proximiio'
]

platform :ios, '13.0'

target 'RnDemoApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  
  target 'RnDemoAppTests' do
    inherit! :complete
    # Pods for testing
  end
  
  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if STATIC_LIBRARIES.include?(pod.name)
        def pod.build_type
          Pod::BuildType.static_library
        end
      end
    end
    $RNMBGL.pre_install(installer)
  end

  post_install do |installer|
    $RNMBGL.post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'NO'
      end

      # https://github.com/facebook/react-native/issues/31034
      if (target.name&.eql?('FBReactNativeSpec'))
        target.build_phases.each do |build_phase|
          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
            target.build_phases.move(build_phase, 0)
          end
        end
      end
    end
  end

end

target 'RnDemoApp-tvOS' do
  # Pods for RnDemoApp-tvOS

  target 'RnDemoApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
